### PR TITLE
Adds `unfurl` input to disable unfurling

### PR DESCRIPTION
**Pull request by aximov**
## What this PR does / Why we need it

This adds `unfurl` input parameter, which is not required and true as default, in order to provide a way to disable `unfurl_links` and `unfurl_media`.

## Which issue(s) this PR fixes

None.

### CODE REVIEW

**Comment by micnncim** [comment]
Thanks, looks good. Can you run yarn build and push the change?

**Comment by aximov** [comment]
@micnncim Done!

**Review by micnncim — APPROVED** [review]
Great, thank you!

**Comment by micnncim** [comment]
@aximov Sorry for being late. I published the new version (https://github.com/actions-ecosystem/action-slack-notifier/releases/tag/v1.1.0), which includes this change.

**Pull request merged**
